export interface Container {
  id: number;
  nombre_contenedor: string;
  tipo: string;
  estado: number;
  descripcionC: string;
  created_at: string;
  updated_at: string;
  empresa_id: number;
  generador_id: number;
  telemetria_id: number;
  set_point: number;
  latitud: number | null;
  longitud: number | null;
  ultima_fecha: string;
  temp_supply_1: number;
  temp_supply_2: number | null;
  return_air: number;
  evaporation_coil: number;
  condensation_coil: number;
  compress_coil_1: number;
  compress_coil_2: number | null;
  ambient_air: number;
  cargo_1_temp: number | null;
  cargo_2_temp: number | null;
  cargo_3_temp: number | null;
  cargo_4_temp: number | null;
  relative_humidity: number | null;
  avl: number;
  suction_pressure: number | null;
  discharge_pressure: number | null;
  line_voltage: number;
  line_frequency: number;
  consumption_ph_1: number;
  consumption_ph_2: number;
  consumption_ph_3: number;
  co2_reading: number | null;
  o2_reading: number | null;
  evaporator_speed: number;
  condenser_speed: number;
  battery_voltage: number | null;
  power_kwh: number | null;
  power_trip_reading: number | null;
  power_trip_duration: number | null;
  suction_temp: number | null;
  discharge_temp: number | null;
  supply_air_temp: number | null;
  return_air_temp: number | null;
  dl_battery_temp: number | null;
  dl_battery_charge: number | null;
  power_consumption: number | null;
  power_consumption_avg: number | null;
  alarm_present: number | null;
  capacity_load: number;
  power_state: number;
  controlling_mode: string;
  humidity_control: number;
  humidity_set_point: number;
  fresh_air_ex_mode: number;
  fresh_air_ex_rate: number | null;
  fresh_air_ex_delay: number | null;
  set_point_o2: number | null;
  set_point_co2: number | null;
  defrost_term_temp: number | null;
  defrost_interval: number | null;
  water_cooled_conde: number | null;
  usda_trip: number | null;
  evaporator_exp_valve: number | null;
  suction_mod_valve: number | null;
  hot_gas_valve: number | null;
  economizer_valve: number | null;
  ethylene: number | null;
  stateProcess: string;
  stateInyection: number | null;
  timerOfProcess: number | null;
  modelo: string | null;
  alarm_number: number | null;
  NA: string;
  ripener_prueba: number;
  defrost_prueba: number | null;
  sp_ethyleno: number;
  extra_1: number;
  extra_2: number;
  imei: string | null;
}

export interface ContainerResponse {
  data: Container[];
  code: number;
  message: string;
}
